### ISSUE TITLE
On windows, "missing README.md file" message when running grunt-nice-package unit tests

### ISSUE THREAD

**Issue by ludoviclefevre** [bahmutov/grunt-nice-package#17]
Hi,

On windows 8, when running grunt-nice-package unit-tests, i get "missing README.md file" error message. Of course, this file is present.

I think the problem is related to glob issue: https://github.com/isaacs/node-glob/issues/123

and getReadmeFiles function:

```
function getReadmeFiles() {
  var fileMatchOptions = {
    nocase: true
  };
  var readmes = glob.sync(process.cwd() + '/readme.md', fileMatchOptions)
      .concat(glob.sync(process.cwd() + '/readme', fileMatchOptions));
  return readmes;
}
```
In glob, process.cwd is the default directory in which to search. So a workaround could be

```
  var readmes = glob.sync('readme.md', fileMatchOptions)
      .concat(glob.sync('readme', fileMatchOptions));
```

I tried and it works on windows.

Your opinion?

Thanks.

Ludovic

**Comment by bahmutov** [comment]
Could you try version 0.9.3 for this problem, please?

**Comment by ludoviclefevre** [comment]
I tried version 0.9.3 but I had the same problem. I think your package is not the problem, the root cause is in node-glob (https://github.com/isaacs/node-glob/issues/123). When the node-glob issue will be fixed, it will resolve this problem.

Thank you for your time.

Ludovic
